Repository Open-Eye-Im-Developer/MoGakGo-FE, pull requests merged in 2024-03, with the labels that each got.

#81 [fix] 프로젝트 생성 폼 한글 입력 2번 되는 문제 수정
  app/project/_hooks/useTagSelect.ts
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#79 [feat] 채팅 UX개선 작업
  app/chat/[id]/_components/Message.tsx
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/_components/MessageList.tsx
  app/chat/[id]/_components/UpScrollButton.tsx
  app/chat/[id]/_hooks/useCustomMessage.tsx
  app/chat/[id]/_hooks/useScroll.tsx
  app/chat/[id]/_types/message.ts
  app/chat/[id]/data.ts
  app/chat/[id]/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#78 [style] 업적 페이지 스타일 수정
  app/achievements/_components/AchievementDrawer.tsx
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/AchievementProgress.tsx
  app/achievements/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#74 [feat] 카카오 장소 검색 호출에 세부 기능 추가 in 프로젝트 생성
  app/api/place/search/route.ts
  app/project/_components/FormPlace.tsx
  app/project/_components/FormTag.tsx
  app/project/_components/FormTime.tsx
  app/project/_components/ProjectCreateDialog.tsx
  app/project/_hooks/useDebounceSearch.ts
  app/project/_hooks/useTagSelect.ts
  app/project/_types/type.d.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#77 [feat] 프로젝트 카드 렌더링 분기 처리
  app/(map)/_components/Map.tsx
  app/project/_components/ButtonRequest.tsx
  app/project/_components/ButtonRotate.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_hooks/useGetRequestListQuery.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#85 [feat] 채팅 api 연결 및 활성화된 채팅방 표시 구현
  app/chat/[id]/_api/index.ts
  app/chat/[id]/_api/useGetChatInfo.ts
  app/chat/[id]/_components/Profile.tsx
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/_types/chatRoom.ts
  app/chat/[id]/_types/message.ts
  app/chat/[id]/page.tsx
  app/chat/_api/index.ts
  app/chat/_api/useGetChats.ts
  app/chat/_components/Chat.tsx
  app/chat/_components/ChatList.tsx
  app/chat/_types/chat.ts
  app/chat/data.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#97 [chore] build 시 에러해결
  app/page.tsx
  app/signup/page.tsx
  next.config.mjs
Labels: bug 🐞, MVP1 🎯

#89 [style] 네비게이션 바 구현
  app/_common/components/NavigationBar.tsx
  app/_common/components/NavigationItem.tsx
  app/_common/components/NavigationProfile.tsx
  app/layout.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#91 [fix] position type 파일명 refactor 이후 잘못된 경로 수정
  app/_common/api/location.ts
  app/_common/store/usePositionStore.ts
  app/_common/types/position.ts
  app/_common/utils/getGeolocation.ts
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/_hooks/useMutationAuthMyLocation.ts
  app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts
Labels: bug 🐞, MVP1 🎯

#83 [feat] 프로젝트 요청 목록 무한스크롤 적용
  app/api/project/request/find/route.ts
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_hooks/useInfiniteScroll.ts
  app/project/_types/type.d.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#93 [feat] 지역별 카드 조회 페이지네이션 로직 구현
  app/(map)/_api/useGetCardList.ts
  app/(map)/_api/useGetRank.ts
  app/(map)/_components/CardList.tsx
  app/(map)/_components/Map.tsx
  app/(map)/_components/ProfileCardItem.tsx
  app/(map)/_tests/formatRegionName.test.ts
  app/(map)/_utils/formatRegionName.ts
  app/_common/api/profile.ts
  app/_common/api/project.ts
  app/_common/components/LoadingSpinner.tsx
  app/_common/components/MapComponent.tsx
  app/project/_components/ButtonFollow.tsx
  app/signup/_components/SignupForm.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#104 [style] 회원가입 스크롤 막음 해제 그 외
  app/_common/hooks/mutation/useDeleteUser.ts
  app/signup/_components/ProfileCard.tsx
  app/signup/_components/SignupFinalStep.tsx
  app/signup/_components/SignupFirstStep.tsx
  app/signup/_components/SignupForm.tsx
  app/signup/_components/SignupSecondStep.tsx
  app/signup/page.tsx
Labels: MVP1 🎯

#105 [fix] AuthStore user 객체 기본값 변경
  app/_common/components/NavigationBar.tsx
  app/_common/store/useAuthStore.ts
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/project/_components/ButtonRequest.tsx
  app/project/_components/ProjectCardFront.tsx
Labels: MVP1 🎯

#92 [feat] 마이페이지 API 연결
  app/_common/api/matching.ts
  app/_common/api/profile.ts
  app/_common/api/project.ts
  app/_common/api/user.ts
  app/_common/components/NavigationProfile.tsx
  app/_common/types/matching.ts
  app/_common/types/profile.ts
  app/_common/types/project.ts
  app/_common/types/user.ts
  app/my-page/_components/EditForm/AchievementField.tsx
  app/my-page/_components/EditForm/AvatarUploadField.tsx
  app/my-page/_components/EditForm/DevelopLanguagesField.tsx
  app/my-page/_components/EditForm/WantedJobsField.tsx
  app/my-page/_components/EditForm/index.tsx
  app/my-page/_components/JandiRating.tsx
  app/my-page/_components/LikeCount.tsx
  app/my-page/_components/MyPageLayout.tsx
  app/my-page/_components/MyProjectHistory.tsx
  app/my-page/_components/MyProjectList.tsx
  app/my-page/_components/MyProjectRequests.tsx
  app/my-page/_components/Profile.tsx
  app/my-page/_components/ProjectCard.tsx
  app/my-page/_components/ProjectCardSkeleton.tsx
  app/my-page/_components/TempCard.tsx
  app/my-page/_hooks/useMutationMatchCancel.ts
  app/my-page/_hooks/useMutationUpdateUser.ts
  app/my-page/_hooks/useQueryMyJandiRating.ts
  app/my-page/_hooks/useQueryMyProjectHistory.ts
  app/my-page/_hooks/useQueryMyProjectList.ts
  app/my-page/_hooks/useQueryMyProjectRequests.ts
  app/my-page/_hooks/useQueryMyReceiveLikeCount.ts
  app/my-page/_hooks/useQueryMySendLikeCount.ts
  app/my-page/_hooks/useQueryUserData.ts
  app/my-page/_util/validation.ts
  app/my-page/constants.ts
  app/my-page/edit/page.tsx
  app/my-page/history/page.tsx
  app/my-page/page.tsx
  app/my-page/types.ts
  app/signup/_type/signup.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#63 [feat] websocket & StompJS 세팅
  app/api/chat/route.ts
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/page.tsx
  app/chat/_types/type.d.ts
  package-lock.json
  package.json
Labels: MVP1 🎯, SPRINT 2 🔥

#110 [hotfix] user 객체, developLanguages 타입 관련 문제 해결
  app/signup/_components/ProfileCard.tsx
  app/signup/_hooks/useMutationSignup.ts
Labels: bug 🐞, MVP1 🎯

#111 [fix] 로그인 시 사용자 정보 전역 스토어 저장 로직 구현
  app/_common/hooks/useSearchTokens.ts
  app/signup/_hooks/useQuerySignUpUser.ts
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#109 [chore] redirects 설정 추가
  next.config.mjs
Labels: MVP1 🎯

#99 [feat] 리뷰 서버 연결 및 리뷰 Mutation 훅 생성
  app/_common/api/project.ts
  app/_common/components/LoadingSpinner.tsx
  app/_common/components/types/review.ts
  app/review/_components/RatingItem.tsx
  app/review/_components/ReviewForm.tsx
  app/review/_constants/rating.tsx
  app/review/_hooks/useMutationReview.ts
  app/review/page.tsx
Labels: bug 🐞, MVP1 🎯

#114 [fix] user 정보 null 오류 수정
  app/chat/[id]/_components/MessageInput.tsx
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#121 [fix] 지도페이지 401 에러 처리
  app/(map)/_api/useGetRank.ts
  app/(map)/_components/Map.tsx
  app/_common/api/project.ts
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#107 [feat] 프로필 카드 찜하기 구현
  app/(map)/_api/useGetCardList.ts
  app/(map)/_api/useToggleLikeProfile.ts
  app/(map)/_components/CardList.tsx
  app/(map)/_components/ProfileCardItem.tsx
  app/_common/api/profile.ts
  app/_common/types/profile.ts
  app/page.tsx
  app/project/_components/ButtonFollow.tsx
  app/project/_components/ButtonLike.tsx
  app/project/_utils/formatMeetingTime.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#129 [chore] react-query devtools 설치
  app/_common/components/ClientProvider.tsx
  package-lock.json
  package.json
Labels: MVP1 🎯, SPRINT 2 🔥

#122 [ feat] 채팅 페이지의 채팅 내용 동기화
  app/api/chat/route.ts
  app/chat/[id]/_components/Message.tsx
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/_hooks/useCustomMessage.tsx
  app/chat/[id]/_hooks/useGetPrevMessageList.ts
  app/chat/[id]/_types/message.ts
  app/chat/[id]/data.ts
  app/chat/[id]/page.tsx
  app/chat/_api/index.ts
  app/chat/_api/useGetChats.ts
  app/chat/_components/Chat.tsx
  app/chat/_components/ChatList.tsx
  app/chat/_types/chat.ts
  app/chat/_types/type.d.ts
  app/chat/data.ts
  app/chat/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#126 [fix] 유저 정보가 없는 경우 지도를 클릭했을 때 화면 막히는 에러 해결
  app/(map)/_components/Map.tsx
  app/_common/utils/redirect.ts
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#127 [feat] 채팅 및 알람 스켈레톤 view 설정
  app/_common/components/ActivityCardSkeleton.tsx
  app/chat/[id]/_api/useGetChatInfo.ts
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/page.tsx
  app/chat/_api/useGetChats.ts
  app/chat/_components/Chat.tsx
  app/chat/_components/ChatList.tsx
  app/chat/data.ts
  app/notification/_api/useGetNotifications.ts
  app/notification/_components/NotificationList.tsx
Labels: MVP2 🧨

#132 [fix] reissue 자동 갱신 버그 해결
  app/_common/api/auth.ts
  app/_common/api/instance.ts
Labels: bug 🐞

#102 [feat] 업적 페이지 조회, 업적 변경 API 연결
  app/_common/api/achievements.ts
  app/_common/api/auth.ts
  app/_common/hooks/useSearchTokens.ts
  app/_common/types/user.ts
  app/achievements/_components/AchievementDrawer.tsx
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/AchievementProgress.tsx
  app/achievements/_hooks/useMutationUserAchievement.ts
  app/achievements/_hooks/useQueryAchievements.ts
  app/achievements/_test/calculateAchievement.test.ts
  app/achievements/_utils/calculateAchievement.ts
  app/achievements/page.tsx
  app/signup/_type/signup.ts
  next.config.mjs
Labels: MVP1 🎯

#144 [style] 대표 폰트 변경
  app/globals.css
  public/Galmuri9.woff2
  tailwind.config.ts
Labels: MVP2 🧨

#153 [chore] next.config.js 설정 변경
  next.config.mjs
Labels: bug 🐞

#150 [style] tailwindCSS Config에 neo-brutalism의 box-shadow 속성을 variable로 생성
  app/globals.css
  tailwind.config.ts
Labels: MVP2 🧨, SPRINT 2 🔥

#157 [refactor] 브랜드 컬러 tailwind config 설정
  tailwind.config.ts
Labels: MVP2 🧨, SPRINT 2 🔥

#131 [fix] 프로젝트, 프로필 카드 조회 페이지네이션 반환값 수정
  app/(map)/_api/useGetCardList.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#161 [style] 지도 컴포넌트 폰트, 배경 스타일 변경
  app/(map)/_components/Map.tsx
  app/(map)/_components/RankInfo.tsx
  app/(map)/_styles/map.css
  app/_common/components/MapComponent.tsx
  tailwind.config.ts
Labels: MVP2 🧨

#151 [feat] 채팅방 활성화 상태 및 나가기 기능 구현
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/_api/index.ts
  app/chat/_api/useDeleteChatRoom.tsx
  app/chat/_components/Chat.tsx
  app/chat/_components/OptionButton.tsx
Labels: MVP2 🧨

#162 [style] dropdown-menu 스타일 수정
  app/_common/shadcn/ui/dropdown-menu.tsx
Labels: MVP2 🧨

#159 [style] shadcn 공통 컴포넌트 커스텀 스타일 적용(select, sheet, tabs, ...)
  app/_common/shadcn/ui/accordion.tsx
  app/_common/shadcn/ui/avatar.tsx
  app/_common/shadcn/ui/badge.tsx
  app/_common/shadcn/ui/card.tsx
  app/_common/shadcn/ui/select.tsx
  app/_common/shadcn/ui/separator.tsx
  app/_common/shadcn/ui/sheet.tsx
  app/_common/shadcn/ui/tabs.tsx
  app/_common/shadcn/ui/toast.tsx
Labels: MVP2 🧨

#164 [refactor] 일반 css를 @apply로 변경
  app/globals.css
Labels: MVP2 🧨, Refactor ⚒️

#134 [refactor] fetch -> axios 마이그레이션
  app/api/match/cancel/route.ts
  app/api/place/search/route.ts
  app/api/project/cancel/route.ts
  app/api/project/create/route.ts
  app/api/project/delete/route.ts
  app/api/project/request/accept/route.ts
  app/api/project/request/create/route.ts
  app/api/project/request/find/route.ts
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_hooks/useGetPrevMessageList.ts
  app/project/_components/ButtonRequest.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_hooks/useAcceptRequestMutation.ts
  app/project/_hooks/useCancelMatchingMutation.ts
  app/project/_hooks/useCancelProjectMutation.ts
  app/project/_hooks/useCreateProjectMutation.ts
  app/project/_hooks/useDebounceSearch.ts
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_hooks/useInfiniteScroll.ts
  app/project/_hooks/useSendRequestMutation.ts
  app/project/_types/type.d.ts
Labels: MVP2 🧨, SPRINT 2 🔥, Refactor ⚒️

#170 [fix] redirects 설정 수정 (회원가입, 리뷰)
  app/_common/hooks/useSearchTokens.ts
  app/review/_components/ReviewForm.tsx
  next.config.mjs
Labels: bug 🐞

#172 [style] shadcn 커스텀 디자인
  app/_common/shadcn/ui/alert-dialog.tsx
  app/_common/shadcn/ui/carousel.tsx
  app/_common/shadcn/ui/menubar.tsx
  app/_common/shadcn/ui/popover.tsx
  app/_common/shadcn/ui/textarea.tsx
  tailwind.config.ts
Labels: MVP2 🧨

#183 [style] accordion variant 옵션 추가
  app/_common/shadcn/ui/accordion.tsx
Labels: new design 🎨

#167 [style] 메인 페이지 서비스 로고 & 움직이는 배경
  app/(map)/_components/Map.tsx
  app/globals.css
  public/images/mapBackgroundImage.png
  public/images/serviceLogoVertical.png
  tailwind.config.ts
Labels: MVP2 🧨

#179 [fix] 프로젝트 생성 시간 설정 오류
  app/project/_constants/formSchema.ts
Labels: bug 🐞, MVP2 🧨

#184 [feat] svg sprite를 사용한 아이콘 컴포넌트 구현
  app/_common/components/Icon.tsx
  app/_common/components/SVGProvider.tsx
  app/layout.tsx
Labels: MVP2 🧨

#136 [feat] 현재 생성한 프로젝트 카드 query hook & 프로젝트 관리 페이지 생성 & 연결
  app/_common/components/NavigationBar.tsx
  app/_common/shadcn/ui/toast.tsx
  app/_common/store/useMatchingStore.ts
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectManageSection.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_hooks/useCancelMatchingMutation.ts
  app/project/_hooks/useCancelProjectMutation.ts
  app/project/_hooks/useCreateProjectMutation.ts
  app/project/_hooks/useGetCurrentProjectQuery.ts
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_hooks/useInvalidateQuery.ts
  app/project/page.tsx
Labels: MVP2 🧨, SPRINT 2 🔥

#193 [fix] 움직이는 배경 이미지 보이지 않는 문제 수정
  app/(map)/_components/Map.tsx
Labels: bug 🐞

#187 [style] button hover => active로 가상선택자 변경
  app/_common/shadcn/ui/button.tsx
Labels: bug 🐞, new design 🎨

#181 [style] 로그인 페이지 새로운 디자인으로 변경
  app/globals.css
  app/login/_components/LoginForm.tsx
  app/login/_components/LoginLogo.tsx
  app/login/_components/StartWithGithubButton.tsx
  app/login/page.tsx
  public/images/login_bg_imgs.png
  public/images/main_logo.webp
  public/pixelroborobo.otf
  tailwind.config.ts
Labels: new design 🎨

#185 [style] review 페이지 새로운 디자인으로 변경
  app/review/_components/RatingItem.tsx
  app/review/_components/ReviewForm.tsx
  app/review/_constants/rating.tsx
  app/review/page.tsx
Labels: new design 🎨

#180 [style] shadcn sonner 토스터 커스텀 적용
  .eslintrc.json
  app/(map)/_api/useToggleLikeProfile.ts
  app/(map)/_components/Map.tsx
  app/_common/api/auth.ts
  app/_common/components/CustomSonner.tsx
  app/_common/components/SVGProvider.tsx
  app/_common/hooks/mutation/useDeleteUser.ts
  app/_common/shadcn/ui/sonner.tsx
  app/_common/utils/getGeolocation.ts
  app/_common/utils/toast.tsx
  app/achievements/_components/AchievementList.tsx
  app/auth-mylocation/_hooks/useMutationAuthMyLocation.ts
  app/chat/_api/useDeleteChatRoom.tsx
  app/layout.tsx
  app/my-page/_components/LikeCancelButton.tsx
  app/my-page/_components/MatchCancelButton.tsx
  app/my-page/_hooks/useMutationCancelLike.ts
  app/my-page/_hooks/useMutationCancelMatch.ts
  app/my-page/_hooks/useMutationUpdateUser.ts
  app/review/_hooks/useMutationReview.ts
Labels: new design 🎨

#198 [refactor] shadcn 컴포넌트 커스텀 디자인하며 넣은 svg 아이콘 컴포넌트화
  app/_common/components/SVGProvider.tsx
  app/_common/shadcn/ui/carousel.tsx
  app/_common/shadcn/ui/menubar.tsx
Labels: Refactor ⚒️

#197 [feat] 마운트 여부 확인하는 HOC 생성
  app/_common/components/SVGProvider.tsx
  app/_common/hoc/withOnMounted.tsx
Labels: MVP2 🧨

#191 [feat] 장소보기 kakao map 이동 구현
  .env.sample
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/_types/chatRoom.ts
Labels: MVP2 🧨

#186 [style] 회원가입, 내 위치인증 페이지 스타일 변경
  app/_common/components/CustomModal.tsx
  app/_common/components/MapComponent.tsx
  app/_common/constants/codeToRegionName.ts
  app/_common/constants/wantedJob.ts
  app/_common/shadcn/ui/form.tsx
  app/_common/types/user.ts
  app/auth-mylocation/_components/AlertMyLocationAuth.tsx
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/_hooks/useMutationAuthMyLocation.ts
  app/my-page/_components/EditForm/WantedJobsField.tsx
  app/my-page/_components/Profile.tsx
  app/signup/_components/LanguageList.tsx
  app/signup/_components/ProfileCard.tsx
  app/signup/_components/SignupCompleteModal.tsx
  app/signup/_components/SignupFinalStep.tsx
  app/signup/_components/SignupFirstStep.tsx
  app/signup/_components/SignupForm.tsx
  app/signup/_components/SignupHeader.tsx
  app/signup/_components/SignupSecondStep.tsx
Labels: bug 🐞, new design 🎨

#138 [feat] athorization 기준의 redirects 설정 구현
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/hooks/mutation/useDeleteUser.ts
  app/_common/hooks/useSearchTokens.ts
  app/_common/utils/cookie.ts
  app/signup/_hooks/useMutationSignup.ts
  middleware.ts
Labels: MVP2 🧨

#209 [style] 프로젝트 생성 카드 스타일 변경
  app/_common/components/ProfileCard.tsx
  app/project/_components/DialogMoreInfo.tsx
  app/project/_components/FormPlace.tsx
  app/project/_components/FormTag.tsx
  app/project/_components/InfoPopover.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectCreateDialog.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_hooks/useGetCurrentProjectQuery.ts
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_types/type.d.ts
Labels: new design 🎨

#194 [style] 네비게이션 하단바 컴포넌트 생성
  app/_common/components/NavigationBottom.tsx
  app/_common/hoc/WithNavigation.tsx
Labels: new design 🎨

#203 [style] 업적 페이지 새로운 디자인으로 변경
  app/_common/components/SVGProvider.tsx
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/ListSortSelect.tsx
  app/achievements/_components/MyAchievement.tsx
  app/achievements/page.tsx
Labels: new design 🎨

#212 [ fix] 카카오 장소 바로가기 API 동작 오류
  app/chat/[id]/_components/ProjectInfo.tsx
Labels: bug 🐞

#220 [fix] import type 오류 수정
  app/_common/components/ProfileCard.tsx
  app/project/_components/DialogMoreInfo.tsx
  app/project/_components/FormPlace.tsx
  app/project/_components/FormTag.tsx
  app/project/_components/FormTime.tsx
  app/project/_components/InfoPopover.tsx
  app/project/_components/PlaceItem.tsx
  app/project/_components/PlaceList.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_hooks/useCreateProjectMutation.ts
  app/project/_hooks/useDebounceSearch.ts
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_hooks/useInfiniteScroll.ts
  app/project/_hooks/useTagSelect.ts
  app/project/_types/type.d.ts
Labels: bug 🐞

#215 [fix] 지도 UX 개선 작업
  app/(map)/_components/CardList.tsx
  app/(map)/_components/EmptyCardList.tsx
  app/(map)/_components/Map.tsx
  app/_common/components/SVGProvider.tsx
  app/_common/hoc/WithOnMounted.tsx
  app/_common/hoc/WithSearchTokens.tsx
  app/auth-mylocation/_components/MyLocationAuth.tsx
  tailwind.config.ts
Labels: MVP2 🧨

#221 [style] sonner toast 스타일, 위치 수정
  app/_common/components/CustomSonner.tsx
  app/_common/utils/toast.tsx
  app/layout.tsx
Labels: new design 🎨

#223 [fix] 캐러샐 카드 닫을 때 끊기며 사라지는 버그 해결
  app/(map)/_components/Map.tsx
Labels: bug 🐞

#207 [refactor] 공용 헤더 네비게이션 path push 추가 및 리팩토링
  app/_common/components/StackNavigator.tsx
  app/chat/[id]/page.tsx
  app/chat/page.tsx
  app/my-page/edit/page.tsx
  app/my-page/history/page.tsx
  app/my-page/likes/page.tsx
  app/my-page/my-project/page.tsx
  app/my-page/page.tsx
  app/my-page/requests/page.tsx
  app/notification/page.tsx
Labels: MVP2 🧨

#227 [fix] 로그인 api 추가로 인하여 login 페이지 수정
  app/(map)/_components/Map.tsx
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/assets/spinner-animation.json
  app/_common/components/LoadingSpinner.tsx
  app/login/_components/LoginForm.tsx
  app/login/_hooks/useMutationLogin.ts
  app/login/page.tsx
Labels: MVP2 🧨, new design 🎨

#217 [style] 프로젝트 페이지 배경 이미지 적용
  app/project/_components/ProjectManageSection.tsx
Labels: new design 🎨

#225 [style] 알림페이지 리디자인 반영
  app/notification/_components/Notification.tsx
  app/notification/_types/notification.ts
  public/images/achievement.svg
  public/images/matching_failed.svg
  public/images/matching_successed.svg
  public/images/request.svg
  public/images/review.svg
Labels: new design 🎨

#234 [fix] 디바이스 높이에 따라 캐러샐 버튼이 하단 네비게이션 바와 겹치는 현상 해결
  app/_common/components/NavigationBar.tsx
  app/_common/components/NavigationBottom.tsx
  app/_common/components/NavigationItem.tsx
  app/_common/components/NavigationProfile.tsx
  app/_common/components/SVGProvider.tsx
  tailwind.config.ts
Labels: bug 🐞

#224 [feat] 업적 리스트 정렬 기능 추가
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/ListSortSelect.tsx
Labels: MVP2 🧨

#233 [style] viewport 색깔 페이지별로 지정
  app/_common/constants/viewPortTheme.ts
  app/_common/utils/generateViewport.ts
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/project/page.tsx
  app/review/page.tsx
Labels: Refactor ⚒️, new design 🎨

#244 [fix] import 에러 수정
  app/achievements/_components/AchievementList.tsx
Labels: bug 🐞

#231 [style] 채팅페이지 리디자인 반영 & 비회원 NavigationBottom redirect 제어
  app/chat/[id]/_components/Message.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/_components/ProjectInfo.tsx
Labels: Refactor ⚒️, new design 🎨

#218 [style] 마이페이지 레이아웃 수정
  app/_common/constants/matchStatus.ts
  app/my-page/_components/DeleteUserButton.tsx
  app/my-page/_components/EditForm/index.tsx
  app/my-page/_components/JandiRating.tsx
  app/my-page/_components/LikeCounter.tsx
  app/my-page/_components/MyAchievements.tsx
  app/my-page/_components/MyProjectHistory.tsx
  app/my-page/_components/MyProjectList.tsx
  app/my-page/_components/MyProjectRequests.tsx
  app/my-page/_components/Profile.tsx
  app/my-page/_components/ProjectCard.tsx
  app/my-page/_components/ProjectCardSkeleton.tsx
  app/my-page/_components/UserCard.tsx
  app/my-page/_components/UserCardSkeleton.tsx
  app/my-page/delete/page.tsx
  app/my-page/edit/page.tsx
  app/my-page/history/page.tsx
  app/my-page/likes/page.tsx
  app/my-page/my-project/page.tsx
  app/my-page/page.tsx
  app/my-page/requests/page.tsx
Labels: new design 🎨

#230 [refactor] WebSocket 구현 방식 리팩토링
  app/_common/hooks/useChat.ts
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/_hooks/useGetPrevMessageList.ts
  app/chat/_types/type.d.ts
Labels: Refactor ⚒️

#246 [fix] 개발 언어 조회에서 imageUrl 추가로 인한 코드 수정
  app/signup/_components/LanguageList.tsx
  app/signup/_test/sortingLanguages.test.ts
  app/signup/_type/signup.ts
  app/signup/_utils/sortingLanguages.ts
  public/images/CSSIcon.webp
  public/images/JSIcon.webp
  public/images/Java.webp
  public/images/Python.webp
  public/images/TSIcon.webp
Labels: MVP2 🧨, new design 🎨

#241 [style] 프로젝트 & 프로필 카드 컴포넌트 스타일 수정
  app/(map)/_components/CardList.tsx
  app/(map)/_components/ProfileCardItem.tsx
  app/_common/components/MapComponent.tsx
  app/_common/components/ProfileCard.tsx
  app/_common/shadcn/ui/accordion.tsx
  app/_common/shadcn/ui/card.tsx
  app/_common/shadcn/ui/popover.tsx
  app/_common/types/profile.ts
  app/globals.css
  app/project/_components/ButtonRotate.tsx
  app/project/_components/DialogMoreInfo.tsx
  app/project/_components/FormTag.tsx
  app/project/_components/InfoPopover.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectCreateDialog.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_components/ProjectManageSection.tsx
  app/project/_hooks/useDebounceSearch.ts
  app/project/_types/type.d.ts
  app/project/page.tsx
Labels: new design 🎨

#252 [style] pwa logo image 수정
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
Labels: new design 🎨

#242 [fix] instance, auth api 수정
  app/(map)/_components/Map.tsx
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/hoc/WithSearchTokens.tsx
  app/_common/hooks/useSearchTokens.ts
  app/login/_hooks/useMutationLogin.ts
  app/login/_types/login.types.ts
  app/signup/_components/SignupForm.tsx
Labels: bug 🐞, Refactor ⚒️

#253 [refactor] 프로젝트 카드 & 프로필 카드 유저 업적 수정
  app/_common/components/ProfileCard.tsx
  app/globals.css
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectManageSection.tsx
Labels: Refactor ⚒️

#256 [fix] 쿠키 저장 방식 변경
  app/_common/api/instance.ts
  app/_common/utils/cookie.ts
  app/api/delete-cookie/route.ts
  app/api/get-cookie/route.ts
  app/api/set-cookie/route.ts
  app/login/_hooks/useMutationLogin.ts
  app/signup/_hooks/useMutationSignup.ts
Labels: bug 🐞, Refactor ⚒️

#262 [fix] 마이페이지 useAuthStore 훅 교체
  app/my-page/history/page.tsx
  app/my-page/likes/page.tsx
  app/my-page/my-project/page.tsx
  app/my-page/requests/page.tsx
Labels: bug 🐞, Refactor ⚒️

#268 [fix] 로그인 페이지 누락된 button type 추가
  app/login/_components/StartWithGithubButton.tsx
Labels: bug 🐞

#257 [feat] GPS 허용 안내 모달 생성
  app/_common/components/CustomSonner.tsx
  app/_common/components/GPSInfoModal.tsx
  app/_common/utils/getGeolocation.tsx
  app/_common/utils/toast.tsx
Labels: MVP2 🧨

#271 [style] 공통 버튼 컴포넌트 텍스트 색상 추가
  app/_common/shadcn/ui/button.tsx
Labels: bug 🐞

#240 [feat] 유저 정보가 없는 경우 하단 네비게이션 바 접근 금지 토스트 추가
  app/(map)/_components/Map.tsx
  app/_common/components/NavigationBottom.tsx
Labels: MVP2 🧨

#249 [style] 서비스 logo svg화
  app/(map)/_components/Map.tsx
  app/_common/components/SVGProvider.tsx
  app/globals.css
  app/login/_components/LoginLogo.tsx
  public/images/serviceLogoVertical.png
  public/pixelroborobo.otf
  tailwind.config.ts
Labels: Refactor ⚒️, new design 🎨

#259 [fix] 업적, 내 위치인증 페이지 수정
  app/_common/components/SVGProvider.tsx
  app/achievements/_components/ListSortSelect.tsx
  app/achievements/page.tsx
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/page.tsx
Labels: Refactor ⚒️, new design 🎨

#276 [feat] 주 언어 비율 표시 모달 추가
  app/_common/api/user.ts
  app/_common/types/user.ts
  app/my-page/_components/Badges.tsx
  app/my-page/_components/DevelopLanguageModal.tsx
  app/my-page/_components/Profile.tsx
  app/my-page/_hooks/useQueryDevelopLanguage.ts
  app/my-page/page.tsx
Labels: MVP2 🧨

#278 [feat] 로그인 안내 모달 추가
  app/_common/shadcn/ui/alert-dialog.tsx
  app/achievements/_hooks/useQueryAchievements.ts
  app/my-page/_components/DeleteUserButton.tsx
  app/my-page/_components/LikeCancelButton.tsx
  app/my-page/_components/LoginRequestModal.tsx
  app/my-page/_components/MyAchievements.tsx
  app/my-page/constants.ts
  app/my-page/edit/page.tsx
  app/my-page/layout.tsx
  app/my-page/page.tsx
Labels: MVP2 🧨

#279 [fix] reissue 자동 갱신 수정
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/utils/cookie.ts
Labels: bug 🐞

#284 [refactor] 채팅, 알람 useInfiniteQuery 호출
  app/_common/components/AnnounceEmptyNotification.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/_api/index.ts
  app/chat/_api/useGetChats.ts
  app/chat/_components/ChatList.tsx
  app/chat/_types/chat.ts
  app/chat/data.ts
  app/my-page/page.tsx
  app/notification/_api/index.ts
  app/notification/_api/useGetNotifications.ts
  app/notification/_components/NotificationList.tsx
  package-lock.json
  package.json
Labels: Refactor ⚒️, new design 🎨

#282 [feat] 로그인 시 스토어에 유저 정보 저장 로직 추가
  app/login/_hooks/useMutationLogin.ts
Labels: MVP2 🧨

#269 [refactor] 모각고 페이지 & 채팅 카드 컴포넌트 수정
  app/_common/types/project.ts
  app/chat/[id]/_components/Message.tsx
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/_components/UpScrollButton.tsx
  app/chat/[id]/page.tsx
  app/chat/_components/Chat.tsx
  app/my-page/_components/MatchCancelButton.tsx
  app/my-page/_components/MyCurrentMatchingProject.tsx
  app/my-page/_components/MyProjectList.tsx
  app/my-page/_components/ProjectCard.tsx
  app/my-page/_hooks/useQueryCurrentMatchingProject.tsx
  app/my-page/_hooks/useQueryProjectDetail.ts
  app/my-page/my-project/page.tsx
  app/my-page/page.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectChatCard.tsx
  app/project/_components/ProjectManageSection.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_constants/messages.ts
  app/project/_hooks/useGetChatRoomIdQuery.ts
Labels: Refactor ⚒️, new design 🎨

#288 [fix] GPS 허용 안내 모달 여러 번 뜨는 버그
  app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts
  app/signup/_components/SignupForm.tsx
Labels: bug 🐞

#287 [fix] 업적 달성시 토스트 알림
  app/_common/api/achievements.ts
  app/_common/components/AchievementModal.tsx
  app/_common/components/WebSocketProvider.tsx
  app/_common/components/types/achievementModal.ts
  app/_common/shadcn/ui/toast.tsx
  app/_common/shadcn/ui/use-toast.ts
  app/_common/types/user.ts
  app/layout.tsx
  app/project/_components/FormPlace.tsx
  app/project/_utils/formatTime.ts
Labels: MVP2 🧨

#289 [style] 리뷰, 업적 페이지 스켈레톤 추가
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/skeleton/AchievementItemSkeleton.tsx
  app/achievements/_components/skeleton/AchievementSkeleton.tsx
  app/achievements/_components/skeleton/MyAchievementSkeleton.tsx
  app/achievements/_hooks/useQueryAchievements.ts
  app/review/_components/ReviewForm.tsx
  app/review/_components/ReviewSkeleton.tsx
  app/review/_constants/rating.tsx
  app/review/page.tsx
Labels: MVP2 🧨, new design 🎨

#286 [fix] 쿠키 삭제시 path 옵션 제공
  app/_common/utils/cookie.ts
  app/api/delete-cookie/route.ts
  app/api/set-cookie/route.ts
  app/login/_hooks/useMutationLogin.ts
  app/signup/_hooks/useMutationSignup.ts
Labels: bug 🐞

#302 [feat] 로그아웃 버튼 추가
  app/login/_hooks/useMutationLogin.ts
  app/my-page/_components/LogoutButton.tsx
  app/my-page/page.tsx
  app/signup/_hooks/useMutationSignup.ts
Labels: MVP1 🎯

#296 [fix] 하단 네비게이션 바 캐러샐과 겹침 현상으로 z-index 낮추기
  app/_common/components/NavigationBottom.tsx
Labels: bug 🐞

#304 [fix] 프로젝트 카드 관련, 기타 수정
  app/(map)/_components/ProfileCardItem.tsx
  app/_common/components/WebSocketProvider.tsx
  app/_common/shadcn/ui/alert-dialog.tsx
  app/_common/types/profile.ts
  app/chat/[id]/_components/MessageContainer.tsx
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/_components/ChatList.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectChatCard.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_hooks/useAcceptRequestMutation.ts
  app/project/_hooks/useCreateProjectMutation.ts
  app/project/_hooks/useGetChatRoomIdQuery.ts
Labels: bug 🐞

#307 [fix] 채팅 웹 소켓 주소 .env로 변경
  app/chat/[id]/_components/MessageContainer.tsx
Labels: bug 🐞

#305 [fix] 업적 페이지 무한 랜더링 오류 수정, 기타 오타 및 오류 수정
  .env.sample
  app/(map)/_components/RankInfo.tsx
  app/_common/api/achievements.ts
  app/achievements/_components/AchievementDrawer.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/ListSortSelect.tsx
  app/achievements/_hooks/useQueryAchievements.ts
  app/achievements/_utils/calculateAchievement.ts
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/login/page.tsx
  app/my-page/page.tsx
  app/project/_components/ProjectCreateDialog.tsx
  app/project/_components/ProjectManageSection.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_constants/statusMessage.ts
  app/project/_hooks/useCancelProjectMutation.ts
  app/project/_hooks/useCreateProjectMutation.ts
Labels: bug 🐞

#300 [feat] 모각고 metadata 설정, 파비콘 변경
  app/favicon.ico
  app/layout.tsx
  public/next.svg
  public/thumbnail.png
  public/vercel.svg
Labels: MVP2 🧨

#315 [style] 다크모드 시 글씨색, 배경색, 뷰포트 색 수정
  app/_common/components/ProfileCard.tsx
  app/_common/components/StackNavigator.tsx
  app/_common/constants/viewPortTheme.ts
  app/_common/shadcn/ui/menubar.tsx
  app/_common/utils/generateViewport.ts
  app/achievements/page.tsx
  app/auth-mylocation/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/my-page/page.tsx
  app/page.tsx
  app/project/_components/ButtonLike.tsx
  app/project/_components/InfoPopover.tsx
  app/project/_components/PlaceItem.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/page.tsx
  app/review/page.tsx
Labels: bug 🐞, new design 🎨

#309 [fix] 배포에서 발견된 문제 수정
  app/_common/shadcn/ui/alert-dialog.tsx
  app/project/_components/ProjectManageSection.tsx
Labels: bug 🐞

#314 [fix] iOS PWA 환경에서 외부 링크 실행시 뷰포트 높이가 줄어드는 버그 해결
  app/(map)/_components/Map.tsx
  app/_common/components/LoadingSpinner.tsx
  app/chat/[id]/page.tsx
  app/globals.css
  app/login/page.tsx
  app/my-page/delete/page.tsx
  app/my-page/edit/page.tsx
  app/my-page/history/page.tsx
  app/my-page/likes/page.tsx
  app/my-page/my-project/page.tsx
  app/my-page/requests/page.tsx
  app/project/page.tsx
  app/review/_components/ReviewSkeleton.tsx
  app/review/page.tsx
  app/signup/_components/SignupForm.tsx
Labels: bug 🐞

#318 [fix] 지역별 프로젝트 밀도 순위 1~3위 데이터 존재 여부 따라 노출 처리
  app/(map)/_components/RankInfo.tsx
  app/_common/components/MapComponent.tsx
Labels: MVP2 🧨

#310 [feat] 지역별 프로필 카드 비회원용 조회 public api 연결
  app/(map)/_api/useGetCardList.ts
  app/(map)/_components/Map.tsx
  app/_common/api/profile.ts
  app/_common/components/NavigationBottom.tsx
Labels: MVP2 🧨

#323 [fix] 업적id를 title로 변경
  app/_common/constants/achievements.ts
  app/project/_components/ProjectCardBack.tsx
Labels: bug 🐞

#320 [style] 움직이는 배경 이미지 다크 모드 대응
  app/_common/constants/viewPortTheme.ts
  app/chat/[id]/_components/ProjectInfo.tsx
  app/globals.css
  public/images/cloud.png
  public/images/cloud_dark.png
  public/images/mapBackgroundImage.png
  public/images/mapBackgroundImage_dark.png
Labels: new design 🎨

#327 [fix] 채팅 페이지 오류 해결
  app/chat/[id]/_components/MessageInput.tsx
  app/chat/_components/Chat.tsx
Labels: bug 🐞

#326 [refactor] 업적 웹소켓 프로토콜 변경
  app/_common/components/WebSocketProvider.tsx
  app/project/_hooks/useGetRequestListQuery.ts
Labels: Refactor ⚒️

#336 [fix] 영등포 영어 오타 수정
  app/_common/components/MapComponent.tsx
Labels: bug 🐞

#332 [fix] 배포에서 발견된 UI/UX 관련 문제
  app/_common/components/NavigationBottom.tsx
  app/_common/shadcn/ui/alert-dialog.tsx
  app/layout.tsx
  app/project/_components/FormTime.tsx
  app/project/_components/ProjectCreateDialog.tsx
Labels: bug 🐞

#321 [hotfix] 데이터 오류로 인해 업적 페이지 임시 수정
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_hooks/useMutationUserAchievement.ts
  app/achievements/_hooks/useQueryAchievements.ts
  app/achievements/_utils/calculateAchievement.ts
Labels: bug 🐞

#343 [refactor] navigate 함수 useRouter 훅으로 대체
  app/_common/components/NavigationBottom.tsx
  app/login/_components/StartWithGithubButton.tsx
  app/my-page/_components/LoginRequestModal.tsx
  app/my-page/_components/LogoutButton.tsx
Labels: Refactor ⚒️

#339 [fix] tanstack-query throwOnError 비활성화
  app/_common/components/ClientProvider.tsx
Labels: bug 🐞

#341 [hotfix] input 클릭 시 축소가 안풀리는 버그 수정
  app/layout.tsx
  app/project/_components/FormPlace.tsx
  app/project/_components/FormTag.tsx
  app/project/layout.tsx
Labels: bug 🐞

#345 [hotfix] 모각고 페이지에서 발생하는 간헐적 Client Exception Error
  app/project/_components/ProjectCreateDialog.tsx
Labels: bug 🐞

#338 [style] 채팅 페이지 누락된 네비게이션 추가
  app/chat/[id]/_components/Message.tsx
  app/chat/_components/ChatList.tsx
  app/chat/page.tsx
Labels: bug 🐞

#349 [fix] pinch zoom, textarea 확대 비활성화
  app/_common/shadcn/ui/textarea.tsx
  app/globals.css
Labels: bug 🐞

#354 [fix] notification type 변경
  app/notification/_components/Notification.tsx
  app/notification/_constant/notificaiton.ts
  app/notification/_types/notification.ts
Labels: bug 🐞

#356 [fix] 업적 변경 후 ui 업데이트 되도록 수정
  app/_common/api/auth.ts
  app/_common/components/ProfileCard.tsx
  app/_common/store/useAuthStore.ts
  app/_common/types/user.ts
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/MyAchievement.tsx
  app/achievements/_hooks/useMutationUserAchievement.ts
  app/achievements/_hooks/useQueryAchievements.ts
  app/my-page/_components/MyAchievements.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/signup/_type/signup.ts
Labels: bug 🐞

#360 hotfix: 업적 변경 버튼 상태 수정
  app/achievements/_components/AchievementItem.tsx
Labels: bug 🐞

#352 [fix] 배포에서 발견된 문제 수정
  app/_common/components/ProfileCard.tsx
  app/_common/components/WebSocketProvider.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardFront.tsx
Labels: bug 🐞

#362 [fix] StackNavigator 레이아웃 처리 방식 flex로 변경
  app/_common/components/StackNavigator.tsx
  app/my-page/page.tsx
Labels: bug 🐞
