Repository Open-Eye-Im-Developer/MoGakGo-FE, pull requests merged in 2024-02, with the labels that each got.

#7 [chore] code formatting 추가
  .eslintrc.json
  .husky/pre-commit
  .prettierrc.json
  app/_common/components/theme-provider.tsx
  app/_common/shadcn/ui/accordion.tsx
  app/_common/shadcn/ui/button.tsx
  app/_common/shadcn/ui/calendar.tsx
  app/_common/shadcn/ui/carousel.tsx
  app/_common/shadcn/ui/checkbox.tsx
  app/_common/shadcn/ui/command.tsx
  app/_common/shadcn/ui/context-menu.tsx
  app/_common/shadcn/ui/dialog.tsx
  app/_common/shadcn/ui/drawer.tsx
  app/_common/shadcn/ui/dropdown-menu.tsx
  app/_common/shadcn/ui/form.tsx
  app/_common/shadcn/ui/label.tsx
  app/_common/shadcn/ui/menubar.tsx
  app/_common/shadcn/ui/navigation-menu.tsx
  app/_common/shadcn/ui/radio-group.tsx
  app/_common/shadcn/ui/resizable.tsx
  app/_common/shadcn/ui/select.tsx
  app/_common/shadcn/ui/sheet.tsx
  app/_common/shadcn/ui/sonner.tsx
  app/_common/shadcn/ui/toast.tsx
  app/_common/shadcn/ui/toaster.tsx
  app/_common/shadcn/ui/toggle-group.tsx
  app/_common/shadcn/ui/toggle.tsx
  app/_common/shadcn/utils.ts
  app/layout.tsx
  package-lock.json
  package.json
Labels: MVP1 🎯, SPRINT 1 🔥

#16 [feat] PWA 작업환경 설정
  app/layout.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/sw.js.map
  public/workbox-07a7b4f2.js
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
Labels: MVP1 🎯, SPRINT 1 🔥

#20 [feat] 사용자 위치 전역 상태관리 생성
  app/_common/store/usePositionStore.ts
  app/_common/types/position.types.ts
  app/_common/utils/getGeolocation.ts
Labels: MVP1 🎯, SPRINT 1 🔥

#17 [feat] 지도 페이지, 지도 컴포넌트 구현
  app/_common/components/MapComponent.tsx
  app/_common/constants/regionCode.ts
  app/map/page.tsx
  tailwind.config.ts
Labels: MVP1 🎯, SPRINT 1 🔥

#35 [feat] axios validateStatus 설정에 따라 response type 추가 설정
  app/_common/test/checkInstanceOfResponseError.test.ts
  app/_common/types/response.types.ts
  app/_common/utils/checkInstanceOfResponseError.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#29 [feat] 프로젝트 카드 컴포넌트, 프로젝트 생성 & 삭제 구현
  .env.sample
  .gitignore
  app/_common/shadcn/ui/dialog.tsx
  app/api/place/search/route.ts
  app/api/project/cancel/route.ts
  app/api/project/create/route.ts
  app/api/project/delete/route.ts
  app/api/project/request/create/route.ts
  app/globals.css
  app/layout.tsx
  app/project/_components/ButtonCancel.tsx
  app/project/_components/ButtonFollow.tsx
  app/project/_components/ButtonRequest.tsx
  app/project/_components/ButtonRotate.tsx
  app/project/_components/ChatBox.tsx
  app/project/_components/FormPlace.tsx
  app/project/_components/FormTag.tsx
  app/project/_components/FormTime.tsx
  app/project/_components/PlaceItem.tsx
  app/project/_components/PlaceList.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectChatCard.tsx
  app/project/_components/ProjectCreateDialog.tsx
  app/project/_components/ProjectCreateForm.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_constants/formSchema.ts
  app/project/_constants/messages.ts
  app/project/_hooks/useDebounceSearch.ts
  app/project/_hooks/useFlip.ts
  app/project/_hooks/usePopupToast.ts
  app/project/_hooks/useTagSelect.ts
  app/project/_hooks/useTime.ts
  app/project/_test/formatTime.test.ts
  app/project/_types/type.d.ts
  app/project/_utils/formatTime.ts
  app/project/page.tsx
  public/images/grass.png
  public/images/profileImage.jpg
Labels: MVP1 🎯, SPRINT 1 🔥

#44 [style] 지도에서 구역 클릭 시 프로젝트 카드 조회 퍼블리싱
  app/_common/components/MapComponent.tsx
  app/_common/constants/regionCode.ts
  app/_common/shadcn/ui/carousel.tsx
  app/map/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#30 [feat] 내 위치 인증 페이지 구현
  app/_common/api/location.ts
  app/_common/constants/codeToRegionName.ts
  app/_common/store/usePositionStore.ts
  app/auth-mylocation/_components/AlertMyLocationAuth.tsx
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/hooks/useMutationAuthMyLocation.ts
  app/auth-mylocation/hooks/useQueryGeoAreaCode.ts
  app/auth-mylocation/page.tsx
  app/layout.tsx
Labels: MVP1 🎯, SPRINT 1 🔥

#43 [feat] 리뷰 컴포넌트 구현
  app/_common/components/CustomModal.tsx
  app/_common/components/review/RatingItem.tsx
  app/_common/components/review/ReviewForm.tsx
  app/_common/components/review/constants/rating.tsx
  app/_common/shadcn/ui/dialog.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#42 [fix] style 속성 브라우저 호환성 버그 수정
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_styles/card.css
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#36 [feat] 지역별 프로젝트 밀도 순위 조회 기능 추가
  app/_common/api/project.ts
  app/_common/components/MapComponent.tsx
  app/layout.tsx
  app/map/_api/useGetRank.ts
  app/map/_components/RankInfo.tsx
  app/map/_styles/map.css
  app/map/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#18 [feat] 회원가입 페이지 구현
  .env.sample
  .gitignore
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/constants/wantedJob.constants.ts
  app/_common/store/useUserStore.ts
  app/_common/types/user.ts
  app/login/_components/LoginForm.tsx
  app/login/_components/StartWithGithubButton.tsx
  app/login/_hooks/useMutationReissueAccessToken.ts
  app/login/_types/login.types.ts
  app/login/page.tsx
  app/signup/_components/LanguageList.tsx
  app/signup/_components/SignupCompleteModal.tsx
  app/signup/_components/SignupFinalStep.tsx
  app/signup/_components/SignupFirstStep.tsx
  app/signup/_components/SignupForm.tsx
  app/signup/_components/SignupHeader.tsx
  app/signup/_components/SignupSecondStep.tsx
  app/signup/_hooks/useMutationDeleteUser.ts
  app/signup/_hooks/useMutationSignup.ts
  app/signup/_hooks/useQuerySignUpUser.ts
  app/signup/_hooks/useSearchTokens.ts
  app/signup/_test/sortingLanguages.test.ts
  app/signup/_type/signup.ts
  app/signup/_utils/sortingLanguages.ts
  app/signup/_utils/validation.ts
  app/signup/page.tsx
  next.config.mjs
  public/images/CSSIcon.webp
  public/images/JSIcon.webp
  public/images/TSIcon.webp
  public/images/cat.webp
  tailwind.config.ts
Labels: MVP1 🎯, SPRINT 1 🔥

#31 [feat] 알람 기능 구현
  .env.sample
  app/_common/components/StackNavigator.tsx
  app/layout.tsx
  app/notification/_api/index.ts
  app/notification/_api/useGetNotifications.ts
  app/notification/_assets/notification.json
  app/notification/_components/AllowBox.tsx
  app/notification/_components/AnnounceEmptyNotification.tsx
  app/notification/_components/ModalDenied.tsx
  app/notification/_components/Notification.tsx
  app/notification/_components/NotificationList.tsx
  app/notification/_types/notification.ts
  app/notification/page.tsx
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
Labels: MVP1 🎯, SPRINT 1 🔥

#52 [feat] 루트 페이지에 지도 페이지 추가
  app/(map)/_api/useGetRank.ts
  app/(map)/_components/RankInfo.tsx
  app/(map)/_styles/map.css
  app/(map)/page.tsx
  app/_common/components/MapComponent.tsx
  app/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#54 [refactor] 지도 컴포넌트 이름 변경 및 폴더 이동
  app/(map)/_components/Map.tsx
  app/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#56 [fix] 지도 확대 시 스크롤 생기는 버그 및 손가락 확대 막기
  app/(map)/_components/Map.tsx
  app/(map)/_components/RankInfo.tsx
  app/_common/components/MapComponent.tsx
Labels: bug 🐞, MVP1 🎯, SPRINT 2 🔥

#37 [feat] 지도 페이지 이동 시 유저 위치 기반 로직 추가
  app/(map)/_components/Map.tsx
  app/_common/api/location.ts
  app/_common/components/MapComponent.tsx
  app/_common/constants/regionCode.ts
  app/_common/store/usePositionStore.ts
  app/_common/utils/getGeolocation.ts
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/hooks/useQueryGeoAreaCode.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#65 [feat] 채팅페이지, 채팅방페이지 view 구현
  app/_common/components/ActivityCard.tsx
  app/_common/components/AnnounceEmptyNotification.tsx
  app/_common/components/StackNavigator.tsx
  app/chat/[id]/_components/Message.tsx
  app/chat/[id]/_components/MessageList.tsx
  app/chat/[id]/_components/Profile.tsx
  app/chat/[id]/_components/ProjectInfo.tsx
  app/chat/[id]/_types/message.ts
  app/chat/[id]/data.ts
  app/chat/[id]/page.tsx
  app/chat/_assets/animation.json
  app/chat/_components/Chat.tsx
  app/chat/_components/ChatList.tsx
  app/chat/data.ts
  app/chat/page.tsx
  app/chat/types/chat.ts
  app/notification/_components/AnnounceEmptyNotification.tsx
  app/notification/_components/Notification.tsx
  app/notification/_components/NotificationList.tsx
  app/notification/_types/notification.ts
  app/notification/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#66 [feat] 프로젝트/프로필 카드 조회 기능 개발
  app/(map)/_api/useGetCardList.ts
  app/(map)/_components/CardList.tsx
  app/(map)/_components/EmptyCardList.tsx
  app/(map)/_components/Map.tsx
  app/_common/api/profile.ts
  app/_common/api/project.ts
  app/_common/types/profile.ts
  app/_common/types/project.ts
  app/_common/types/response.ts
  app/_common/types/response.types.ts
  app/_common/utils/checkInstanceOfResponseError.ts
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_test/formatMeetingTime.test.ts
  app/project/_utils/formatMeetingTime.ts
Labels: MVP1 🎯, SPRINT 2 🔥

#57 [feat] 개발 언어 조회 서버 연결 그 외
  app/(map)/_components/Map.tsx
  app/_common/api/languages.ts
  app/_common/assets/spinner-animation.json
  app/_common/components/CustomModal.tsx
  app/_common/components/LoadingSpinner.tsx
  app/_common/hooks/queries/useQueryDevelopLanguages.ts
  app/_common/store/useAuthStore.ts
  app/_common/store/useModalStore.ts
  app/auth-mylocation/_components/AlertMyLocationAuth.tsx
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/_hooks/useMutationAuthMyLocation.ts
  app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts
  app/signup/_components/LanguageList.tsx
  app/signup/_components/ProfileCard.tsx
  app/signup/_components/SignupCompleteModal.tsx
  app/signup/_components/SignupFinalStep.tsx
  app/signup/_components/SignupFirstStep.tsx
  app/signup/_components/SignupForm.tsx
  app/signup/_components/SignupSecondStep.tsx
  app/signup/_hooks/useMutationDeleteUser.ts
  app/signup/_hooks/useMutationSignup.ts
  app/signup/_test/sortingLanguages.test.ts
  app/signup/_type/signup.ts
  app/signup/_utils/sortingLanguages.ts
  public/images/Java.webp
  public/images/Python.webp
Labels: MVP1 🎯, SPRINT 2 🔥

#62 [style] 업적 페이지 view 구현
  app/achievements/_components/AchievementItem.tsx
  app/achievements/_components/AchievementList.tsx
  app/achievements/_components/AchievementProgress.tsx
  app/achievements/_test/calculateAchievement.test.ts
  app/achievements/_utils/calculateAchievement.ts
  app/achievements/page.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#64 [fix] reissue 자동 갱신 로직 수정, 메인에서 token search hook 추가, token search HOC 구현
  app/(map)/_components/Map.tsx
  app/_common/api/auth.ts
  app/_common/api/instance.ts
  app/_common/components/WithSearchTokens.tsx
  app/_common/hooks/useSearchTokens.ts
  app/login/_hooks/useMutationReissueAccessToken.ts
  app/signup/_components/SignupForm.tsx
Labels: MVP1 🎯, SPRINT 2 🔥

#72 [fix] GeoAreaCode 타입 추가 후 관련 파일 수정
  app/(map)/_components/Map.tsx
  app/_common/types/position.ts
  app/auth-mylocation/_components/MyLocationAuth.tsx
  app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts
Labels: SPRINT 2 🔥

#47 [feat] 프로젝트 요청 조회 & 수락 & 매칭 취소 기능
  app/api/match/cancel/route.ts
  app/api/project/request/accept/route.ts
  app/api/project/request/find/route.ts
  app/globals.css
  app/project/_components/BadgeAdditional.tsx
  app/project/_components/ButtonRotate.tsx
  app/project/_components/ProjectCardBack.tsx
  app/project/_components/ProjectCardContainer.tsx
  app/project/_components/ProjectCardFront.tsx
  app/project/_components/ProjectChatCard.tsx
  app/project/_components/ProjectRemoveDialog.tsx
  app/project/_constants/statusMessage.ts
  app/project/_hooks/useGetRequestListQuery.ts
  app/project/_hooks/usePopupToast.ts
  app/project/_types/type.d.ts
Labels: MVP1 🎯, SPRINT 2 🔥
